[package]
name = "elgamal_encryption"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"